name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # pin@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a # pin@v3.0.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm ci

      # TODO add tests here
