name: new pull request

on:
  pull_request:
    branches: [ main ]

jobs:
  new-pr:
    permissions:
      pull-requests: write
      contents: read

    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest

    steps:
      # Comment on new PR requests with deployment instructions
      - name: checkout
        uses: actions/checkout@v3.5.3
      - name: comment
        uses: GrantBirki/comment@462538298fbbd513aea4492f82d6582060b997ec # pin@v2.0.5
        continue-on-error: true
        with:
          file: .github/new-pr-comment.md
