name: new pull request

on:
  pull_request:
    branches: [ main ]

jobs:
  new-pr:
    permissions:
      pull-requests: write
      contents: read

    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest

    steps:
      # Comment on new PR requests with deployment instructions
      - name: checkout
        uses: actions/checkout@v3.5.0
      - name: comment
        uses: GrantBirki/comment@60344bb4027deed85442d23f562f2257291f9b5e # pin@v2.0.4
        continue-on-error: true
        with:
          file: .github/new-pr-comment.md
